bbs / 一旦実装. テストまだ.
chichiri0126/toy_app pull request #1
Opened 2021-03-05 09:28 UTC by chichiri0126

2021-03-05 09:41 UTC, nari requested changes
@nitta-tatsunori URLの設計についてコメントしてみました！こちらで結構全体的に変わると思いますので、修正チャレンジしてみてください！

2021-03-05 09:41 UTC, nari commented on config/routes.rb
> +  delete '/users/:user_id/comment/:comment_id' => 'user_comments#delete', as: 'comment_delete'
こちらの場合だと、ディレクトリに `user_id` を含めなくても、[sessionでログインしているユーザーが取得できそう](https://github.com/chichiri0126/toy_app/blob/f0f9b38c9df861ac9821e755c20a54308b19d87d/app/helpers/sessions_helper.rb#L20)なので、無理にディレクトリパラメータに入れる必要は無いかと思います！

なので、以下のような書き方でRestfulにスッキリ書けると思います。
```ruby
recources :threads do
  resources :comments, only: [:new, :create, :destory]
end
```

2021-03-05 09:46 UTC, nari commented on config/routes.rb
> +  delete '/users/:user_id/comment/:comment_id' => 'user_comments#delete', as: 'comment_delete'
`rake routes | grep threads`

2021-03-08 02:01 UTC, nari requested changes
@chichiri0126 細かい点ですが、レビューさせていただきました！

2021-03-08 02:01 UTC, nari commented on app/views/topics/show.html.erb
> +  <% if @topic.topic_comments.any? %>
こちらって、何を確かめようとしている感じでしょうか？
`any?` は[こちら](https://docs.ruby-lang.org/ja/latest/method/Enumerable/i/any=3f.html)によると、
`すべての要素が偽である場合に false を返します。真である要素があれば、ただちに true を返します` とあるのですが、多分やりたいことって、 `present?` メソッドなのかなと推察しますが、いかがでしょうか？
参考: https://qiita.com/aeroastro/items/b58228decb7094af7594

2021-03-08 02:09 UTC, chichiri0126 commented on app/views/topics/show.html.erb
> +  <% if @topic.topic_comments.any? %>
やりたかったことはぬるぽチェックでしたが、 `present?` は空チェックもしてくれて方が便利そうなので使わせていただきます！

2021-03-08 12:13 UTC, nari approved these changes
LGTM

2021-08-24 08:06 UTC, closed without merging